server:
  port: 8084
  servlet:
    context-path: /eaisp-consents-enterprise-api
spring:
  application:
    name: Consent-Enterprise-Api


  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: syam
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect